# Generated by Django 4.2.7 on 2023-12-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_studentcourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
